import { Response, NextFunction } from "express";
import { agentService } from "../services/agent.service.js";
import { sendSuccess } from "../utils/response.js";
import { AuthRequest } from "../middleware/auth.js";

export class AgentController {
  async health(_req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const result = await agentService.health();
      sendSuccess(res, result, "AI agent health retrieved");
    } catch (error) {
      next(error);
    }
  }

  async ask(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const { question, currentDay, currentSlide } = req.body;
      const result = await agentService.chat(
        req.user!.id,
        question,
        currentDay,
        currentSlide,
      );
      sendSuccess(res, result, "AI response received");
    } catch (error) {
      next(error);
    }
  }

  async generateQuiz(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const { day, difficulty, count } = req.body;
      const result = await agentService.generateQuiz(day, difficulty, count);
      sendSuccess(res, result, "Quiz generated by AI");
    } catch (error) {
      next(error);
    }
  }

  async analyzeLevel(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const userId = req.body.userId || req.user!.id;
      const result = await agentService.analyzeLevel(userId);
      sendSuccess(res, result, "Level analyzed");
    } catch (error) {
      next(error);
    }
  }
}

export const agentController = new AgentController();
